[project]
name = "docling-checkout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.6.0",
    "docling>=2.31.0",
    "numpy>=1.26.4",
    "scipy>=1.15.2",
]
